name: Build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
    build:
      runs-on: self-hosted
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with: 
            fetch-depth: 0
        
        - name: Add platformio_sample.ini
          working-directory: ./
          run: cp platformio_sample.ini platformio.ini
        
        - name: Add config file
          working-directory: ./rancilio-pid/rancilio-pid/
          run: cp userConfig_sample.h userConfig.h
        
        - name: Run PlatformIO
          run: ~/.platformio/penv/bin/platformio run
